### PR TITLE
add NE example

### PR DESCRIPTION
**Pull request by bstabler**
@steventrev to reconcile unwanted differences before merge.  We just want to add the NE example.

### CODE REVIEW

**Comment by steventrev** [comment]
@bstabler This was my first go at syncing via Git Bash. I believe this PR can be merged now.

**Comment by steventrev** [comment]
Upon review, it seems that I am missing /data/atlanta/ on my branch. Although no conflicts on the surface, I may have missed something in the merge. I attempted to follow [Syncing a fork](https://help.github.com/articles/syncing-a-fork/), but may have missed these files.

**Comment by steventrev** [comment]
Keep scratching my head on tidying up previous commits, but I think we are okay now. Much Git to learn.

**Comment by bstabler** [comment]
@steventrev - thanks, and I added a legend title so you might want to pull master back to your fork

https://github.com/RSGInc/ActivityViz/commit/9bc5a070da1ba0a52f4f7530d6b4a7bb655a1c10

**Pull request merged**
